version: "2"
run:
  concurrency: 4
  go: "1.24"
linters:
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: (.+)\.go$
        text: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
severity:
  default: error
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
